#!/usr/bin/env node
/**
 * Build-time TTS generator.
 *
 * Synthesizes one audio clip per label using Azure Speech, writing
 * assets/tts/<lang>/<id>.mp3 plus a static require() map for Metro.
 *
 * This never runs in the app. It runs on a developer machine, the resulting
 * mp3s are committed, and the app only ever plays files.
 *
 *   export AZURE_SPEECH_KEY=...
 *   export AZURE_SPEECH_REGION=westeurope
 *
 *   node scripts/generate-tts.mjs --lang hy --ids 0,1,3,17,88   # audition
 *   node scripts/generate-tts.mjs --lang hy --all               # full pack
 *   node scripts/generate-tts.mjs --lang hy --all --force       # re-synthesize
 */

import { readFile, writeFile, mkdir, readdir, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

const VOICES = {
  hy: 'hy-AM-AnahitNeural',
  ru: 'ru-RU-SvetlanaNeural',
  en: 'en-US-JennyNeural',
};

const LABEL_FILES = {
  hy: 'assets/lables/labelsHy.json',
  ru: 'assets/lables/labelsRu.json',
  en: 'assets/lables/labelsEn.json',
};

// 24kHz/48kbps mono mp3: ~6KB per second of speech.
const OUTPUT_FORMAT = 'audio-24khz-48kbitrate-mono-mp3';
const CONCURRENCY = 4;
const MAX_RETRIES = 5;

function parseArgs(argv) {
  const args = { lang: 'hy', all: false, force: false, ids: null, voice: null, rate: null, audition: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--all') args.all = true;
    else if (a === '--force') args.force = true;
    else if (a === '--audition') args.audition = true;
    else if (a === '--lang') args.lang = argv[++i];
    else if (a === '--voice') args.voice = argv[++i];
    else if (a === '--rate') args.rate = argv[++i];
    else if (a === '--ids') args.ids = argv[++i].split(',').map((s) => Number(s.trim()));
    else throw new Error(`Unknown argument: ${a}`);
  }
  if (!args.all && !args.ids) {
    throw new Error('Pass --all for the full pack, or --ids 0,1,2 to audition a few.');
  }
  return args;
}

const escapeXml = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
   .replace(/"/g, '&quot;').replace(/'/g, '&apos;');

function ssml(text, voice, locale, rate) {
  const inner = rate ? `<prosody rate="${escapeXml(rate)}">${escapeXml(text)}</prosody>` : escapeXml(text);
  return `<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xml:lang="${locale}">`
       + `<voice name="${voice}">${inner}</voice></speak>`;
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

async function synthesize({ text, voice, locale, rate, key, region }) {
  const endpoint = `https://${region}.tts.speech.microsoft.com/cognitiveservices/v1`;
  let lastErr;
  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    const res = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Ocp-Apim-Subscription-Key': key,
        'Content-Type': 'application/ssml+xml',
        'X-Microsoft-OutputFormat': OUTPUT_FORMAT,
        'User-Agent': 'smart-sight-tts-build',
      },
      body: ssml(text, voice, locale, rate),
    });

    if (res.ok) return Buffer.from(await res.arrayBuffer());

    // 429 is the free tier's rate limit; back off and retry rather than fail the run.
    if (res.status === 429 || res.status >= 500) {
      const wait = Number(res.headers.get('retry-after')) * 1000 || 2 ** attempt * 1000;
      lastErr = new Error(`HTTP ${res.status}`);
      await sleep(wait);
      continue;
    }
    const body = await res.text().catch(() => '');
    if (res.status === 401) {
      throw new Error(`401 Unauthorized — check AZURE_SPEECH_KEY and that AZURE_SPEECH_REGION (${region}) matches the resource. ${body}`);
    }
    throw new Error(`HTTP ${res.status} ${body}`);
  }
  throw lastErr ?? new Error('exhausted retries');
}

async function mapWithConcurrency(items, limit, fn) {
  const results = new Array(items.length);
  let cursor = 0;
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      while (cursor < items.length) {
        const i = cursor++;
        results[i] = await fn(items[i], i);
      }
    })
  );
  return results;
}

async function writeRequireMap(lang, outDir) {
  const files = (await readdir(outDir)).filter((f) => f.endsWith('.mp3'));
  const ids = files.map((f) => Number(path.basename(f, '.mp3'))).sort((a, b) => a - b);

  // Metro cannot resolve require() with a computed path, so the map has to be static.
  const lines = ids.map((id) => `  ${id}: require('@assets/tts/${lang}/${id}.mp3'),`);
  const body = `// AUTO-GENERATED by scripts/generate-tts.mjs — do not edit by hand.
// Regenerate with: node scripts/generate-tts.mjs --lang ${lang} --all

export const ${lang}Clips: Record<number, number> = {
${lines.join('\n')}
};

export const ${lang}ClipCount = ${ids.length};
`;
  const dest = path.join(ROOT, 'src/services/tts', `${lang}Clips.ts`);
  await mkdir(path.dirname(dest), { recursive: true });
  await writeFile(dest, body, 'utf8');
  return { dest, count: ids.length };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const key = process.env.AZURE_SPEECH_KEY;
  const region = process.env.AZURE_SPEECH_REGION;
  if (!key || !region) {
    console.error('Missing AZURE_SPEECH_KEY and/or AZURE_SPEECH_REGION in the environment.');
    process.exit(1);
  }

  const labelFile = LABEL_FILES[args.lang];
  if (!labelFile) throw new Error(`No label file configured for lang "${args.lang}"`);
  const voice = args.voice ?? VOICES[args.lang];
  if (!/^[a-zA-Z0-9-]+$/.test(voice)) throw new Error('Invalid voice identifier.');
  const locale = voice.split('-').slice(0, 2).join('-');

  const labels = JSON.parse(await readFile(path.join(ROOT, labelFile), 'utf8'));
  const selected = args.all ? labels : labels.filter((l) => args.ids.includes(l.id));
  if (!selected.length) throw new Error('No labels matched the given --ids.');

  const outDir = args.audition
    ? path.join(ROOT, 'artifacts/tts-audition', voice)
    : path.join(ROOT, 'assets/tts', args.lang);
  await mkdir(outDir, { recursive: true });

  const todo = selected.filter(
    (l) => args.force || !existsSync(path.join(outDir, `${l.id}.mp3`))
  );
  const skipped = selected.length - todo.length;

  console.log(`voice:    ${voice}  (${locale})`);
  console.log(`region:   ${region}`);
  console.log(`labels:   ${selected.length} selected, ${skipped} already present, ${todo.length} to synthesize`);
  if (!todo.length) {
    console.log('Nothing to do. Pass --force to re-synthesize.');
  } else {
    const t0 = Date.now();
    let done = 0;
    await mapWithConcurrency(todo, CONCURRENCY, async (label) => {
      const buf = await synthesize({
        text: label.name, voice, locale, rate: args.rate, key, region,
      });
      await writeFile(path.join(outDir, `${label.id}.mp3`), buf);
      done++;
      if (done % 25 === 0 || done === todo.length) {
        process.stdout.write(`  ${done}/${todo.length}\r`);
      }
    });
    const secs = (Date.now() - t0) / 1000;
    console.log(`\nsynthesized ${todo.length} clips in ${secs.toFixed(1)}s`);
  }

  let bytes = 0;
  for (const f of await readdir(outDir)) {
    if (f.endsWith('.mp3')) bytes += (await stat(path.join(outDir, f))).size;
  }
  console.log(`pack size: ${(bytes / 1024 / 1024).toFixed(2)} MB in ${outDir}`);

  if (!args.audition) {
    const { dest, count } = await writeRequireMap(args.lang, outDir);
    console.log(`wrote ${path.relative(ROOT, dest)} (${count} entries)`);
  }

  const chars = selected.reduce((n, l) => n + l.name.length, 0);
  console.log(`billed characters this run: ~${todo.reduce((n, l) => n + l.name.length, 0)} (selection total ${chars})`);
}

main().catch((err) => {
  console.error(`\n${err.message}`);
  process.exit(1);
});
